language: python
install:
- pip install -r ./requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: NDULYkGum2yXdF/DHwvwB6J+Lt42jw0Gjs1yGjzngYHfhw0+GfbsXeWYOEfNF9gMSwJhD3wu8HC5JmL3N7tKUeHV3eDy8gZBXCx3DhRJLJrPq84Y0OGht4H0pc+kEPPOhWryN3Xh5w/214+w6BEq4IEUSLWsGXjKi0Qsewdesq5DNoKvaQfxhc296xNHQtgIjLhv2wqUuM8AlLCIAtOqb8GWtOunNScYz49oPBzUOfXCeNT5x197MR5H90BQm41K01BOqQ8FasefwNSy2MEtRLBwXXC5k7mITc2GD6PtTLzCt3WJKiAWz5GOV7HlXJvqjl7KBbk9/PY2zsR5v/HkxnZNwLqbFT4J42JvR5UX3w7qvWqXIn+Hy5NJe2Y5X8JMZ9QxxUpBmzfKAOoE3u79f4NPP1mSLQ1Q3Ng7q93k2mVUpbPxJh02vVVWYpLfv7bfE0pSTzDxNw7R/U3RTnLhKETNXGLYBD2w6VC8x7IWFNJW/OGG2QVbQ6TPPEXQYjLmkWxvb+vQAJExZm/dz4gGVL7hUBIAsxYVgtUgo6FRU9j10FJ/rV+n1Uxo/9hPF586c33y1Av620t4lQBiBWc9SATXaz1CNmSYpAbv8i6TBfj9QO5HB9khkr8PyDO39ZPegNj5Bit2vG2seEKUJoM472QyGv/F51/yoHmwJDDFHZ8=
  app: needless-youth-unemployment
  on: main
