language: python
install:
- pip install -r ./NeedlessYouthUnemployment/requirements.txt
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: zcuLm4xtE6OY82kFgbAy2iUVAdAD+x2xIK1xmAlmSNiH/fe73biPzPuHkzdMZNIh/MvlYWHHXO+ieQQaJGvjIum+4hlkQ2r85hRXg9fCLQ7kuUy6M1aL+YoXU1SwBlaaMkwv0GvwBYN6Pv94OzQE1qZZHQVEf/o4bIhHTXZifre6/sfjWwv4V/JgY4boMh5zVavvEhSDmhiW8T+ac8be7aE22P+QIR32AZCOhx2qVIEXLhU75lMHjm0rJlLbrMzLRKdyXdCf9v3CqrHd44nqf8pcmKvfaV1KPAcmtTUgsz7cMAZQzXpwdOP4V/s6pI9HrUsmwW7zE0Z2antwyFgctifwdntnMZiiiI0WeHH8drWeJfzy7L5GBZ6u/FMlsLuffWWCPCyvha1jE3nv5n62xtgCxFoSJPjc8r7g2o8tiUdIkZXVwx81G3cVOpsBoQd3sw0rFz6SW96dOFy2qLC+Qb4adwLWLtmXFczYKqwzPyTk8Ntqr6js7J7zJ/Ft2QKRcZtE652LZ7M9v3BjPVtYOopumfc8cEmMsvrdIXCK8ED94NRdyOzTPNrUsAe1NYcYOMj9w9PHooqIVpv2jU1zxFRyz8LYLijWXEgtFelXQGQxkZT7zDJULMkLAfJYNdcgr13lvTPgciodOYEBBwh0/6XjYjcP+YlXe/I2IrjUL9c=
  app: needless-youth-unemployment
  on: main
